sudo: required
services:
  - docker

before_install: 
  - docker build -t samba73/mcclient -f ./client/Dockerfile.dev ./client
  - docker build -t samba73/mcnginx -f ./nginx/Dockerfile.dev ./nginx
  - docker build -t samba73/mcserver ./server/Dockerfile.dev ./server
  - docker build -t samba73/mcworker ./worker/Dockerfile.dev ./worker

 script:
  - docker run -e CI=true samba73/mcclient npm test   
  - docker run -e CI=true samba73/mcserver npm test
  - docker run -e CI=true samba73/mcworker npm test

 after_success:
   - docker build -t samba73/mcclient ./client
   - docker build -t samba73/mcnginx ./nginx
   - docker build -t samba73/mcserver ./server
   - docker build -t samba73/mcworker ./worker

   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

   - docker push samba73/mcclient
   - docker push samba73/mcnginx
   - docker push samba73/mcserver
   - docker push samba73/mcworker 

